name: NPM publish CD workflow

on:
  push:

jobs:
  buildTestDeploy:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
            matrix:
                node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test

      - name: Configure package registry
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      
      - name: Publish to NPM
        run: |
          npm version patch
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Push to Github
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}